version: "3.3"

services:
  my-docker:
    build: .
    command: "ping"
    ports:
      - "80:9000"
    networks:
      - web
    depends_on:
      - redis
  redis:
    image: redis:latest
    networks:
      - web


networks:
  web:
    driver: "bridge"